#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
BASE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
echo $BASE_DIR

sudo apt-get install -y cmake exuberant-ctags vim tmux zsh

sudo chsh -s /bin/zsh $USER

# curl 'ftp://ftp.u-aizu.ac.jp/pub/eclipse/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz' | sudo tar xzf --directory /opt/eclipse
# curl 'http://sourceforge.net/projects/eclim/files/eclim/2.3.4/eclim_2.3.4.jar/download' | java -jar

git clone https://github.com/robbyrussell/oh-my-zsh.git     $BASE_DIR/bash.config/oh-my-zsh
git clone https://github.com/gmarik/Vundle.vim.git          $BASE_DIR/vim.config/vim/bundle/Vundle.vim
git clone https://github.com/junegunn/fzf.git               $BASE_DIR/vim.config/vim/fzf.vim

bash $BASE_DIR/vim.config/vim/fzf.vim/install

echo "source $BASE_DIR/bash.config/main.sh" >> ~/.zshrc
echo "source $BASE_DIR/vim.config/vimrc" >> ~/.vimrc
echo "export FZF_TMUX=0" >> ~./zshrc

ln -s $BASE_DIR/vim.config/vim ~/.vim
ln -s $BASE_DIR/tmux.config/tmux.conf ~/.tmux.conf

vim +PluginInstall +qall

cd $BASE_DIR
