alias lah='la -h'
alias las='ls -ah'
alias composer='composer -v'
alias gr='noglob grep -ns'
alias rgr='noglob rgrep -ns'
alias amux='tmux attach'
alias httpserver='python -m SimpleHTTPServer'
alias gl='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit --all'
